# **TUGAS NUMPY**

---

Nama: Very Fachrurozi

NIM: 235150207111003

Setelah mengikuti workshop Numpy dan Pandas, tentunya kalian sudah mulai memahami hal-hal apa saja yang akan dilakukan oleh Data Scientist dengan Numpy. Sekarang, saatnya mengukur kemampuan kalian dari apa yang telah kalian dapatkan pada workshop sebelumnya.

**Deadline: Jumat, 21 Februari 2025**


# **📊 Numpy Exercise 📊**

Selamat datang di latihan eksplorasi data menggunakan **Numpy**!  

---

In [2]:
import numpy as np

## **📌 Soal 1: Regresi Linear** 📝

Saat offline/online assessment kemarin ada persoalaan **Regresi Linear**, nah coba kamu buat menggunakan python dan numpy termasuk poin-poin berikut: <br>
✅ Fungsi regresi mampu menerima array A dan array B dan memprediksi slope dan intercept<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X <br>

In [9]:
def linear_regression(a, b, x_pred):
    a = np.array(a)
    b = np.array(b)
    
    a_mean = np.mean(a)
    b_mean = np.mean(b)
    
    b1 = np.sum((a - a_mean) * (b - b_mean))//np.sum((a - a_mean)**2)
    b0 = b_mean - b1 * a_mean
    
    y_pred = b0 + b1 * x_pred
    return b1, b0, y_pred
    
a = [1, 2, 3, 4, 5]
b = [2, 4, 6, 8, 10]
x_pred = 6
b1, b0, prediction = linear_regression(a, b, x_pred)
print(f"Intercept: {b1:.2f}, Slope: {b0:.2f}, Prediksi untuk X={x_pred}: {prediction:.2f}")

Intercept: 2.00, Slope: 0.00, Prediksi untuk X=6: 12.00


## **📌 Soal 2: Regresi Polinomial** 📝

Saat offline/online assessment kemarin ada persoalan **Regresi Linear**, nah sekarang coba kamu buat **Regresi Polinomial** menggunakan Python dan NumPy, termasuk poin-poin berikut:<br>
✅ Fungsi regresi mampu menerima array A dan array B serta menyesuaikan data dengan polinomial derajat tertentu.<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X.<br>
✅ Hasil regresi mencetak koefisien polinomial yang dihasilkan.<br>

In [13]:
def polynomial_regression(a, b, d):

    koefisien = np.polyfit(a, b, d)
    
    print("Koefisien polinomial:", koefisien)
    
    poly = np.poly1d(koefisien)
    
    return poly

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 5, 10, 17, 26])

d = 2
model = polynomial_regression(x, y, d)

x_new = 6
predicted = model(x_new)
print(f"Prediksi untuk x={x_new}: y={predicted}")

Koefisien polinomial: [ 1.00000000e+00 -2.26948902e-14  1.00000000e+00]
Prediksi untuk x=6: y=37.000000000000064


## **📌 Soal 3: Random Values Array** 📝

Pertama-tama, buatlah **Array Integer 10x10x10** dengan elemen **random** dan carikan:<br>
1️⃣ Cari elemen minimum dan maksimum dalam array tersebut?<br>
2️⃣ Carilah rata-rata dan median seluruh elemen dalam array tersebut?<br>

In [26]:
a = np.random.randint(0,30,(10,10,10))
a

array([[[ 4,  4,  0,  4,  1,  3, 25,  2,  0, 23],
        [23, 11,  5, 25, 14, 29,  2, 12, 15, 20],
        [ 8, 15, 23,  0, 27,  9,  5, 10,  4, 29],
        [ 6,  7,  2,  6, 29, 17, 21,  2, 13, 14],
        [ 8, 16,  8,  8,  8, 29, 11,  4, 18,  3],
        [ 3, 20, 26, 13, 25, 28,  2, 16, 14, 16],
        [23, 12, 23, 13, 11, 18, 13, 16,  1,  9],
        [29, 23, 16, 29, 19, 19, 27,  0, 17, 27],
        [ 4,  3, 26,  8, 18, 20,  3,  8,  2,  6],
        [18, 15, 24,  4, 29, 11,  4, 16, 24, 13]],

       [[ 9, 12, 24,  7,  4, 19, 29, 14, 17, 28],
        [15, 25, 11, 14,  0, 26, 28, 22, 11, 16],
        [21, 29, 10, 26, 22, 21,  8, 25, 20, 17],
        [23,  5,  0,  6, 18,  2, 21, 26,  9, 10],
        [21, 19, 27, 10,  2, 24, 23, 29, 27, 28],
        [11,  7, 16,  2, 13, 25, 20, 22, 11,  8],
        [14, 10,  9, 18,  8,  0, 22, 23, 29, 12],
        [ 8,  8,  9, 25, 29,  3,  5,  4, 23, 19],
        [ 3, 16, 21,  4,  8,  9, 10, 28, 12,  5],
        [20, 27,  6,  7, 18, 13, 25,  3, 13, 22]

In [27]:
minimum = np.min(a)
maxsimum = np.max(a)
print(f"Element Minimum : {minimum} , & Element Maksimal : {maxsimum}" )

Element Minimum : 0 , & Element Maksimal : 29


In [28]:
mean = np.mean(a)
median = np.median(a)
print(f"Mean : {mean}, & Median : {median}")

Mean : 14.354, & Median : 14.0


## **📌 Soal 4: 2D Array Shenanigans** 📝

Tugas kamu disini adalah membuat **Array 2D** sesuai ketentuan masing-masing soal: <br>
1️⃣ Buatlah **array 10x10** yang memiliki angka "5" sebagai bingkai di seluruh tepi luar dan bagian dalam (selain array) berisi "8"? <br>
2️⃣ Buatlah **array 2d 8x8** dengan pola seperti **checkboard/catur** (1 untuk kotak hitam, 0 untuk kotak putih)?<br>
3️⃣ Buatlah **array 2d 15x15** dengan aturan sebagai berikut:
- Jika suatu angka dapat dibagi 2, isi dengan 2.
- Jika suatu angka dapat dibagi 3, isi dengan 3.
- Jika suatu angka dapat dibagi 5, isi dengan 5.
- Jika suatu angka dapat dibagi oleh lebih dari satu kondisi (misal, 6 bisa dibagi 2 & 3), maka simpan gabungan angka tersebut (misal, 6 → "23", 15 → "35").
- Jika tidak memenuhi kondisi apa pun, isi dengan 0.

In [32]:
a_array = np.full((10,10),8)
a_array[0,:] = 5
a_array[-1,:] = 5
a_array[:,0] = 5
a_array[:,-1] = 5
a_array

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [33]:
b_array = np.zeros((8,8), dtype=int)
b_array[1::2, ::2] = 1
b_array[::2, 1::2] = 1
b_array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [34]:
angka = np.arange(1, 226).reshape(15,15)
c_array = np.full(angka.shape," ", dtype=object)

for i in range (15):
    for j in range(15):
        nilai = angka[i,j]
        hasil = ""
        if nilai % 2 == 0:
            hasil += "2"
        if nilai % 3 == 0:
            hasil += "3"
        if nilai % 5 == 0:
            hasil += "5"
        c_array[i,j] = hasil if hasil else "0"
        
print(c_array)

[['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0

## **📌 Soal 5: Time & Date** 📝

Kamu disini diminta untuk memanfaatkan fitur numpy untuk tanggal: <br>
1️⃣ Bagaimana dengan numpy, kamu bisa mendapatkan tanggal hari ini, kemarin dan esok hari?<br>
2️⃣ Tampilkan hari yang ada di bulan Mei tahun 2020?<br>

In [44]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ", yesterday)

today = np.datetime64('today', 'D')
print("Today: ", today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Yestraday:  2025-02-19
Today:  2025-02-20
Tomorrow:  2025-02-21


In [35]:
result = np.datetime64('2020-05','M')
result

numpy.datetime64('2020-05')

## **📌 Soal 6: Slicing** 📝

Jika diketahui array `A`, maka buatlah program untuk mendapatkan elemen dibawah ini:
```python
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])
```

1️⃣ Ambil elemen yang berada pada baris `ke-4` dan kolom `ke-2` dari array `A` <br>
2️⃣ Buat `array 2D` yang hanya berisi bilangan prima dari `A` <br>
3️⃣ Ambil elemen-elemen yang berada di tepi luar dari array `A` dan gabungkan menjadi `Satu array 1D`. <br>
4️⃣ Dapatkan subbarray berikut:
```python
[[20, 40, 60],
 [80, 100, 120],
 [140, 160, 180],
 [200, 220, 240],
 [260, 280, 300]]
```
5️⃣ Dapatkan subbarray berikut:
```python
 [[30, 40],
 [90, 100],
 [150, 160],
 [210, 220]]
```

## **📌 Soal 7: Ekspansi Array** 📝

Jika kamu memiliki array ***Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]***, buatlah kode untuk membuat array R berupa: <br>
***R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]***?