# **TUGAS NUMPY**

---

Nama: Very Fachrurozi

NIM: 235150207111003

Setelah mengikuti workshop Numpy dan Pandas, tentunya kalian sudah mulai memahami hal-hal apa saja yang akan dilakukan oleh Data Scientist dengan Numpy. Sekarang, saatnya mengukur kemampuan kalian dari apa yang telah kalian dapatkan pada workshop sebelumnya.

**Deadline: Jumat, 21 Februari 2025**


# **📊 Numpy Exercise 📊**

Selamat datang di latihan eksplorasi data menggunakan **Numpy**!  

---

In [1]:
import numpy as np

## **📌 Soal 1: Regresi Linear** 📝

Saat offline/online assessment kemarin ada persoalaan **Regresi Linear**, nah coba kamu buat menggunakan python dan numpy termasuk poin-poin berikut: <br>
✅ Fungsi regresi mampu menerima array A dan array B dan memprediksi slope dan intercept<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X <br>

In [2]:
def linear_regression(a, b, x_pred):
    a = np.array(a)
    b = np.array(b)
    
    a_mean = np.mean(a)
    b_mean = np.mean(b)
    
    b1 = np.sum((a - a_mean) * (b - b_mean))//np.sum((a - a_mean)**2)
    b0 = b_mean - b1 * a_mean
    
    y_pred = b0 + b1 * x_pred
    return b1, b0, y_pred
    
a = [1, 2, 3, 4, 5]
b = [2, 4, 6, 8, 10]
x_pred = 6
b1, b0, prediction = linear_regression(a, b, x_pred)
print(f"Intercept: {b1:.2f}, Slope: {b0:.2f}, Prediksi untuk X={x_pred}: {prediction:.2f}")

Intercept: 2.00, Slope: 0.00, Prediksi untuk X=6: 12.00


## **📌 Soal 2: Regresi Polinomial** 📝

Saat offline/online assessment kemarin ada persoalan **Regresi Linear**, nah sekarang coba kamu buat **Regresi Polinomial** menggunakan Python dan NumPy, termasuk poin-poin berikut:<br>
✅ Fungsi regresi mampu menerima array A dan array B serta menyesuaikan data dengan polinomial derajat tertentu.<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X.<br>
✅ Hasil regresi mencetak koefisien polinomial yang dihasilkan.<br>

In [3]:
def polynomial_regression(a, b, d):

    koefisien = np.polyfit(a, b, d)
    
    print("Koefisien polinomial:", koefisien)
    
    poly = np.poly1d(koefisien)
    
    return poly

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 5, 10, 17, 26])

d = 2
model = polynomial_regression(x, y, d)

x_new = 6
predicted = model(x_new)
print(f"Prediksi untuk x={x_new}: y={predicted}")

Koefisien polinomial: [ 1.00000000e+00 -2.26948902e-14  1.00000000e+00]
Prediksi untuk x=6: y=37.000000000000064


## **📌 Soal 3: Random Values Array** 📝

Pertama-tama, buatlah **Array Integer 10x10x10** dengan elemen **random** dan carikan:<br>
1️⃣ Cari elemen minimum dan maksimum dalam array tersebut?<br>
2️⃣ Carilah rata-rata dan median seluruh elemen dalam array tersebut?<br>

In [4]:
a = np.random.randint(0,30,(10,10,10))
a

array([[[ 3, 18, 11, 21, 25, 19,  3, 20, 24, 21],
        [26, 26,  9, 26, 29, 19, 23,  3, 28,  7],
        [ 2, 22,  5,  5, 13, 21,  0,  2,  6, 11],
        [ 5,  6, 17,  4,  3,  3,  6,  9, 22, 11],
        [ 0,  2, 14, 24,  5, 16, 14, 17,  5, 23],
        [28,  8, 24,  3,  2,  7,  3, 29, 24,  0],
        [ 2,  2, 19, 27, 12, 27, 10, 28,  4,  1],
        [14, 27,  1,  5, 20, 28, 12, 11, 20, 21],
        [28, 16, 29, 19, 15, 24,  7, 27, 28, 12],
        [11,  7,  9, 17,  0,  2, 26, 26,  1,  2]],

       [[ 8,  2, 25,  2,  4, 18,  3, 26, 26, 27],
        [17,  0, 21,  5, 14, 12, 28,  3, 27, 27],
        [ 3,  3, 28,  7, 18, 17, 28,  4, 21, 17],
        [25,  5,  6, 14, 16, 10, 22,  3,  6, 28],
        [10, 15, 12, 17, 23,  0, 23, 22, 16, 27],
        [16,  5, 16, 12, 19, 19, 25,  0,  7, 11],
        [12,  4,  5,  8, 18, 15, 16, 13, 17,  9],
        [28,  3, 25, 18, 17, 14, 21, 10, 23, 11],
        [ 6, 18,  4,  4,  3,  3, 12, 18,  5,  0],
        [ 3, 15, 26, 23, 28,  6, 28, 21, 29,  2]

In [5]:
minimum = np.min(a)
maxsimum = np.max(a)
print(f"Element Minimum : {minimum} , & Element Maksimal : {maxsimum}" )

Element Minimum : 0 , & Element Maksimal : 29


In [6]:
mean = np.mean(a)
median = np.median(a)
print(f"Mean : {mean}, & Median : {median}")

Mean : 14.121, & Median : 14.0


## **📌 Soal 4: 2D Array Shenanigans** 📝

Tugas kamu disini adalah membuat **Array 2D** sesuai ketentuan masing-masing soal: <br>
1️⃣ Buatlah **array 10x10** yang memiliki angka "5" sebagai bingkai di seluruh tepi luar dan bagian dalam (selain array) berisi "8"? <br>
2️⃣ Buatlah **array 2d 8x8** dengan pola seperti **checkboard/catur** (1 untuk kotak hitam, 0 untuk kotak putih)?<br>
3️⃣ Buatlah **array 2d 15x15** dengan aturan sebagai berikut:
- Jika suatu angka dapat dibagi 2, isi dengan 2.
- Jika suatu angka dapat dibagi 3, isi dengan 3.
- Jika suatu angka dapat dibagi 5, isi dengan 5.
- Jika suatu angka dapat dibagi oleh lebih dari satu kondisi (misal, 6 bisa dibagi 2 & 3), maka simpan gabungan angka tersebut (misal, 6 → "23", 15 → "35").
- Jika tidak memenuhi kondisi apa pun, isi dengan 0.

In [7]:
a_array = np.full((10,10),8)
a_array[0,:] = 5
a_array[-1,:] = 5
a_array[:,0] = 5
a_array[:,-1] = 5
a_array

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [8]:
b_array = np.zeros((8,8), dtype=int)
b_array[1::2, ::2] = 1
b_array[::2, 1::2] = 1
b_array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [9]:
angka = np.arange(1, 226).reshape(15,15)
c_array = np.full(angka.shape," ", dtype=object)

for i in range (15):
    for j in range(15):
        nilai = angka[i,j]
        hasil = ""
        if nilai % 2 == 0:
            hasil += "2"
        if nilai % 3 == 0:
            hasil += "3"
        if nilai % 5 == 0:
            hasil += "5"
        c_array[i,j] = hasil if hasil else "0"
        
print(c_array)

[['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0

## **📌 Soal 5: Time & Date** 📝

Kamu disini diminta untuk memanfaatkan fitur numpy untuk tanggal: <br>
1️⃣ Bagaimana dengan numpy, kamu bisa mendapatkan tanggal hari ini, kemarin dan esok hari?<br>
2️⃣ Tampilkan hari yang ada di bulan Mei tahun 2020?<br>

In [10]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Kemarin: ", yesterday)

today = np.datetime64('today', 'D')
print("Hari ini: ", today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Esok hari: ", tomorrow)

Kemarin:  2025-02-20
Hari ini:  2025-02-21
Esok hari:  2025-02-22


In [12]:
start = np.datetime64('2020-05-01')
end = np.datetime64('2020-05-31')

dates = np.arange(start, end + np.timedelta64(1, 'D'), dtype='datetime64[D]')

for date in dates:
    print(date)

2020-05-01
2020-05-02
2020-05-03
2020-05-04
2020-05-05
2020-05-06
2020-05-07
2020-05-08
2020-05-09
2020-05-10
2020-05-11
2020-05-12
2020-05-13
2020-05-14
2020-05-15
2020-05-16
2020-05-17
2020-05-18
2020-05-19
2020-05-20
2020-05-21
2020-05-22
2020-05-23
2020-05-24
2020-05-25
2020-05-26
2020-05-27
2020-05-28
2020-05-29
2020-05-30
2020-05-31


## **📌 Soal 6: Slicing** 📝

Jika diketahui array `A`, maka buatlah program untuk mendapatkan elemen dibawah ini:
```python
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])
```

1️⃣ Ambil elemen yang berada pada baris `ke-4` dan kolom `ke-2` dari array `A` <br>
2️⃣ Buat `array 2D` yang hanya berisi bilangan prima dari `A` <br>
3️⃣ Ambil elemen-elemen yang berada di tepi luar dari array `A` dan gabungkan menjadi `Satu array 1D`. <br>
4️⃣ Dapatkan subbarray berikut:
```python
[[20, 40, 60],
 [80, 100, 120],
 [140, 160, 180],
 [200, 220, 240],
 [260, 280, 300]]
```
5️⃣ Dapatkan subbarray berikut:
```python
 [[30, 40],
 [90, 100],
 [150, 160],
 [210, 220]]
```

In [14]:
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])

In [ ]:
# elemen yang berada pada baris ke-4 dan kolom ke-2 dari array A
A[3,1]

200

In [28]:
# array 2d bilangan prima dari A
def prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_mask = np.vectorize(prime)(A)
primes = A[prime_mask]

if primes.size > 0:
    primes_2D = primes.reshape(-1, primes.shape[0] // 2)
    print(primes_2D)
else:
    print("Tidak ada bilangan prima")

Tidak ada bilangan prima


In [20]:
# Ambil elemen-elemen di tepi luar dan gabungkan menjadi array 1D
tepi_atas = A[0, :]
tepi_bawah = A[-1, :]
tepi_kiri = A[1:-1, 0]
tepi_kanan = A[1:-1, -1]
tepi_luar = np.concatenate([tepi_atas, tepi_kanan, tepi_bawah[::-1], tepi_kiri[::-1]])
tepi_luar

array([ 10,  20,  30,  40,  50,  60, 120, 180, 240, 300, 290, 280, 270,
       260, 250, 190, 130,  70])

In [21]:
# Dapatkan subarray [[20, 40, 60], [80, 100, 120], ...]
subarray = A[:, 1::2]
print(subarray)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]
 [200 220 240]
 [260 280 300]]


In [22]:
# Dapatkan subarray [[30, 40], [90, 100], ...]
subarray_5 = A[:4, 2:4]
print(subarray_5)

[[ 30  40]
 [ 90 100]
 [150 160]
 [210 220]]


## **📌 Soal 7: Ekspansi Array** 📝

Jika kamu memiliki array ***Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]***, buatlah kode untuk membuat array R berupa: <br>
***R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]***?

In [25]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])

print("R =\n", R)

R =
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
